language: java
jdk: oraclejdk8
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
deploy:
  provider: heroku
  api_key:
    secure: B4ivUIUKFnv/j6i0QT+Jhg2hCa5EVPkKerPBn/PgcSnt/6twboVfbEPvG8McrhbeM2sWGU3jZATbiaQExwdMbQw78mQugxbi9Ix9qfANn5qUpF8vpKw3KQAdY3cLBx+fpQUIT0IVoosjf/G5cyobponc9Gei2kaqVMWTNodru7XqaluBxhFc7jSYof9RvfitKfmE7jSl+pwks/ENmfkD9Ii7RfY8RMt2i3Ny4bbz8MPukJi6uQIgB5nXvFRcvUEb4ZvMy0UArnn2RGjI6XByS8oxPG9W9+KD7of8yRNAN1wNKZnM0tMeEipzW4A4A3/8uVIdplr03faMBEqzNGx/DUTRICljrGmMn4UujYGZHvb/iyi1bGui1851gKm98npkhKoLg9bB3X7+nwY+jnlqbOKUgGqkRkam+K8/CTzIX7ByOjdlEvf/DQwbt1y+quQbiYcK74bR7po344Ber+4L7CrQn3e1S5xjkec5g+GwJz5Zbv3LjZkFLcsF7bPJw4+xknUg5T4qRd0QqKQdVq9ZxCVyS865KeVR3SmVpfVf01E7L//xHLPmDbSZK8wgHjcOEnOYOhlSTS+FT+6FQvkXBh0uCKk7HdEIxxdSFfOvRE6SWcG5YdD7NJM/9KBGAIKncwjLgyV0w37rzAqlF6xy6D950tZahnv+nGS3McBpf7k=
  app: still-falls-13018
  on:
    repo: chekalin/hikes
addons:
  sonarqube:
    token:
      secure: MCjxsh5Jy57BY5LBUsty3d+ZGeQJE9mbuXIXX8RwCJImldYXvs51JvNk0UDox1Ey0An/sMhXZhMa803I/Sb9AhQ/jPH2yXplXq7k7vHB0xkavf1UL1dWIIfTz5qGvAC7yc1Kcr2b+FLxKCb89mRUYAz/EslaittCsWPBKyBfmqn/3fizoPvvTd43BJZkhVN6EhxYYOBMfTHWb+B1pRMjcCQ6FCqlYVeTXRWN90wSIIE/ignkS++QcPUfdze9KsvGP42vcUkhjoScdxuBBgCASuRqcSqTXsC4NwmzVjR381Zh+94/gGsI2/YQCuZqJnhHPYkLtn9YHgsecZHl9azJ8Zs44x3tpxBNzp2fsoPtYob/CoGT+3FxcrmzbsFpckSOFRhi2df73BPwI6Vd06iayVxgLbw0LN/oLRG4XpbGWWuU75hhtAW0WHVbEmg/Qqb5sizuzCK3eDpmh5nvxaMr/wLZCw0o9lBCf/jdi/+yClVZ+5u0Gr2SmY8Mn+RaU60PMtANpZ7ZkCLg2XXyMab9F8ogl1Qedyjsp1noCI9+sqjUpc4OOqKboQfh/KFAMHRbZHIyPKj5/AsQA9pt8irjYSWlYyzGyzSiiVZTfxzjJoH5Da/mUr+oF9x5KFPe7Z+3qKdJBfTC8iNl38CISGWU7Q9Znj7WOc1/D+cNEQh/Fc0=
